[tool.poetry]
name = "sneact"
version = "0.1.1"
description = "Sneact is a python library for building user interfaces"
readme = "readme.md"
authors = ["Kiselev Nikolay <ceo@machineand.me>"]
homepage = "https://machineand.me/sneact?f=pypi"
repository = "https://github.com/machineandme/sneact"
keywords = ["html", "web", "drs", "sneact", "jsless", "frontend"]
classifiers = [
	"Development Status :: 1 - Planning",
	"Intended Audience :: Developers",
	"Topic :: Internet :: WWW/HTTP :: Dynamic Content",
	"Topic :: Religion",
	"Topic :: Software Development :: Libraries",
	"Topic :: Text Processing :: Markup :: HTML",
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5"
black = "20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
