---
- name: "install /etc/network/interfaces.d/interface-openvpn.cfg"
  template:
    src: interface-openvpn.cfg.j2
    dest: /etc/network/interfaces.d/interface-openvpn.cfg
  register: interface

- name: bring {{ network_secondary_interface }}:1 up
  shell: |
    set -ex
    ifup {{ network_secondary_interface }}:1
  when: interface is changed

- name: apt-get install openvpn nftables
  apt:
    name: [openvpn, nftables]
    state: present

- name: net.ipv4.ip_forward=1
  shell: |
    set -ex
    sed -i -e '/net.ipv4.ip_forward/s/.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
    sysctl -p

- name: nftables
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    force: "{{ openvpn_overwrite_nftables_conf }}"

- name: systemctl enable nftables
  systemd:
    name: nftables
    enabled: yes

- name: nft -f /etc/nftables.conf
  shell:
    nft -f /etc/nftables.conf
  changed_when: False

- name: cp -r /usr/share/easy-rsa /etc/openvpn/
  shell:
    cp -r /usr/share/easy-rsa /etc/openvpn
  args:
    creates: /etc/openvpn/easy-rsa

- name: /etc/openvpn/easy-rsa/vars
  template:
    src: vars.j2
    dest: /etc/openvpn/easy-rsa/vars

- name: ./easyrsa init-pki
  shell: |
    set -ex
    ./easyrsa init-pki
    yes | ./easyrsa build-ca nopass
    echo server | ./easyrsa gen-req server nopass
    echo yes | ./easyrsa sign-req server server
    ./easyrsa gen-dh
    openvpn --genkey --secret ta.key
    ./easyrsa gen-crl
    cp pki/crl.pem ta.key pki/ca.crt pki/private/server.key pki/issued/server.crt pki/dh.pem /etc/openvpn
  args:
    creates: /etc/openvpn/server.key
    chdir: /etc/openvpn/easy-rsa

- name: /etc/openvpn/easy-rsa/create-client.sh
  template:
    src: create-client.sh.j2
    dest: /etc/openvpn/easy-rsa/create-client.sh
    mode: 0755

- name: mkdir -p /etc/openvpn/ccd
  file:
    state: directory
    path: /etc/openvpn/ccd

- name: /etc/openvpn/server.conf
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
  register: server

- name: systemctl enable openvpn@server ; systemctl start openvpn@server
  systemd:
    name: openvpn@server
    state: restarted
    enabled: yes
  when: server is changed
