[tool.poetry]
name = "pygit_annek"
version = "0.1.3"
description = "A CLI wrapper around Pygithub"
authors = ["Michael MacKenna <mmackenna@unitedfiregroup.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
PyGithub = "^1.53"

[tool.poetry.dev-dependencies]
mdv = "^1.7.4"
pylint = "^2.6.0"
keyring = "^21.5.0"

[tool.poetry.scripts]
pygit = 'pygit_annek.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
