[tool.poetry]
name = "r2pyapi"
version = "0.1.2"
description = "High level radare2 python API"
license = "Apache-2.0"
readme = "README.md"
include = ["LICENSE"]
authors = ["Koh M. Nakagawa <tsunekou1019@gmail.com>"]
keywords = ["radare2", "scripting"]

[tool.poetry.dependencies]
python = "^3.8"
r2pipe = "^1.5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.770"
flake8 = "^3.7.9"
isort = "^4.3.21"
black = "^19.10b0"
pytest-datadir = "^1.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
