[tool.black]
line-length = 88
include = '\.pyi?$'
target = ["py38"]
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.poetry]
name = "flatplan"
version = "1.0.2"
description = "Flatplan is a tool that groups all resources and providers specified in a Terraform plan file into a list"
authors = ["Egon Braun <egon@mundoalem.io>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4"
coloredlogs = "^14.0"
fire = "^0.3"

[tool.poetry.dev-dependencies]
pytest = "^6.1"
importlib-metadata = {version = "^3.1.1", python = "<=3.8"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
flatplan = "flatplan:main"
