[tool.poetry]
authors = ["docyx <oliverxur@gmail.com>"]
classifiers = [
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Topic :: Internet",
  "Typing :: Typed",
]
description = "A lightweight, component-based HTML builder"
documentation = "https://github.com/docyx/genjuice"
keywords = ["html", "template", "css", "web"]
license = "MIT"
name = "genjuice"
readme = "README.md"
repository = "https://github.com/docyx/genjuice"
version = "0.1.1"

[tool.poetry.dependencies]
bleach = "^3.2.1"
python = "^3.8"

[tool.poetry.dev-dependencies]
beautifulsoup4 = "^4.9.3"
black = "^20.8b1"
flake8 = "^3.8.4"
pytest = "^6.1.2"
requests = "^2.25.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
