[tool.poetry]
name = "dj-pony.applied-migrations-checker"
version = "0.1.2"
description = "Check that all django database migrations have been applied."
authors = ["Samuel Bishop <sam@techdragon.io>"]
license = "MIT"
packages = [
    { include = "dj_pony" },
]


[tool.poetry.dependencies]
python = "^3.7"
django = ">=1.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
